import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { WebSocketProvider } from "../components/WebSocketProvider";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import MobileBottomBar from "../components/MobileBottomBar";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'], weight: ['400','500','600','700'] });

export const metadata: Metadata = {
  title: "VedaAI | AI Assessment Creator",
  description: "Generated by VedaAI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased overflow-hidden print:h-auto print:overflow-visible">
      <body className={`h-screen w-screen flex font-sans ${inter.className} bg-[#F3F4F6] overflow-hidden text-[#111827] print:h-auto print:overflow-visible print:bg-white print:w-auto print:block`}>
        <WebSocketProvider>
          <div className="flex h-screen w-screen overflow-hidden bg-[#F3F4F6] p-[16px] gap-[16px] print:h-auto print:w-auto print:overflow-visible print:p-0 print:bg-white print:block">
            <aside className="hidden md:flex w-[280px] min-w-[280px] h-full bg-white rounded-[24px] shadow-sm flex-col overflow-hidden z-20 print:hidden">
              <Sidebar />
            </aside>

            <div className="flex flex-col flex-1 min-w-0 h-full overflow-hidden gap-[16px] print:h-auto print:overflow-visible print:block print:gap-0">
              <header className="h-[64px] min-h-[64px] bg-white rounded-[24px] shadow-sm flex items-center shrink-0 w-full z-10 print:hidden">
                <Navbar />
              </header>

              <main className="flex-1 overflow-auto bg-transparent rounded-[24px] print:overflow-visible print:h-auto print:rounded-none relative pb-[80px] md:pb-0">
                {children}
              </main>

              <MobileBottomBar />
            </div>
          </div>
          <Toaster position="top-right" />
        </WebSocketProvider>
      </body>
    </html>
  );
}
